version: '3.8'

services:
  nashville-radio:
    build: .
    container_name: oasis-radio
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./app/stations.json:/data/stations.json
      - ./app/cities.json:/data/cities.json
      - ./app/streamdeck_layout.json:/data/streamdeck_layout.json
      - ./app/siriusxm.json:/data/siriusxm.json
      - /dev/snd:/dev/snd
    devices:
      - /dev/snd
    group_add:
      - audio
    environment:
      - ALSA_CARD=0
      - STATIONS_FILE=/data/stations.json
      - CITIES_FILE=/data/cities.json
      - LAYOUT_FILE=/data/streamdeck_layout.json
